local DB = {
	[70418]={tk='Bane', tv='Погибель',
		dk='^Reduces the casting time of your Shadow Bolt by (.+) sec and your Soul Fire by (.+) sec%.$',
		dv='Сокращает время произнесения заклинания "Стрела Тьмы" на %s сек, а "Ожог души" на %s сек.'},
	[70458]={tk='Ruin',tv='Разгром',
		dk='^Increases the critical strike damage bonus of your Destruction spells by (.+)%.$',
		dv='Увеличивает бонус к критическому урону от заклинаний категории "Разрушение" на %s.'},
	[70635]={tk='Mayhem',tv='Хаос',
		dk='^When activated, increases the critical strike chance of your next Destruction spell by (.+)%.$',
		dv='При активации повышает вероятность критического удара вашего следующего заклинания Разрушения на %s.'},
	[70656]={tk='Sadism',tv='Садизм',
		dk='^Your spell critical strikes have a (.+) chance to restore (.+) Mana%.$',
		dv='Ваши критические удары заклинаниями с вероятностью %s восстанавливают %s маны.'},
	[70926]={tk='Aftermath',tv='Последствия',
		dk='^Gives your Destruction spells a (.+) chance to daze the target for (.+) sec%.$',
		dv='Заклинания разрушения с вероятностью %s вызывают у цели оцепенение на %s сек.'},
	[70945]={tk='Pyroclasm',tv='Огнесдвиг',
		dk='^Gives your Rain of Fire, Hellfire, and Soul Fire spells a (.+) chance to stun the target for (.+) sec%.$',
		dv='Ваши заклинания "Огненный ливень", "Адское Пламя" и "Ожог Души", получают %s шанс оглушить цель на %s сек.'},
	[70956]={tk='Cataclysm',tv='Катаклизм',
		dk='^Reduces the Mana cost of your Destruction spells by (.+)%.$',
		dv='Снижает затраты маны на заклинания разрушения на %s.'},
	[70959]={tk='Intensity',tv='Напряжение',
		dk='^Reduces the chance for enemies to resist your Destruction spells by (.+) and gives you a (.+) chance to resist interruption caused by damage while casting or channeling any Destruction spell%.$',
		dv='Снижает шанс противников сопротивляться вашим заклинаниям разрушения на %s и дает вам %s-й шанс к сопротивлению прерывания, вызванному уроном при произнесении или поддержании любого заклинания разрушения.'},
	[71047]={tk='Emberstorm',tv='Бушующее пламя',
		dk='^Increases the damage done by your Fire spells by (.+)%.$',
		dv='Увеличивает урон от ваших заклинаний огня на %s.'},
	[71068]={tk='Shadowburn',tv='Ожог Тьмы',
		dk='^Instantly blasts the target for (.+) to (.+) Shadow damage%.  If the target dies within (.+) sec of Shadowburn, and yields experience or honor, the caster gains a Soul Shard%.$',
		dv='Мгновенно наносит цели от %s до %s ед. урона от темной магии. В случае смерти цели в течение %s сек. после применения "Ожога Тьмы" и получения при этом опыта или чести чернокнижник также получает осколок души.'},
	[71125]={tk='Conflagrate',tv='Поджигание',
		dk='^Ignites a target that is already afflicted by Immolate, dealing (.+) to (.+) Fire damage and consuming the Immolate spell%.$',
		dv='Поджигает цель, уже находящуюся под воздействием вашего заклинания "Жертвенный огонь", с нанесением ей %s - %s ед. урона от огня и снятием заклинания "Жертвенный огонь".'},
	[71138]={tk='Devastation',tv='Разоритель',
		dk='^Increases the critical strike chance of your Destruction spells by (.+)%.$',
		dv='Увеличивает вероятность критического удара ваших заклинаний разрушения на %s.'},
	[71161]={tk='Shadowstorm',tv='Буря теней',
		dk='^Increases the damage done by your Shadow spells by (.+)%.$',
		dv='Увеличивает урон от ваших заклинаний тьмы на %s.'},
	[71322]={tk='Shock and Awe',tv='Шок и Трепет',
		dk='^Stuns the target for (.+) sec%. While stunned, the target receives an additional (.+) damage from all sources and cannot be healed%.$',
		dv='Оглушает цель на %s сек. Во время оглушения цель получает дополнительно %s урона от всех источников и не может быть излечена.'},
	[71349]={tk='Demonic Power',tv='Демоническая сила',
		dk='^Reduces the casting time of your Imp\'s Firebolt spell by (.+) sec and increases the critical strike chance of your Succubus\' Lash of Pain ability by (.+)%.$',
		dv='Сокращает время произнесения заклинания "Огненная стрела" вашего беса на %s сек и увеличивает вероятность критического удара способности "Всплеск боли" вашей суккубы на %s.'},
	[71430]={tk='Feeding Demons',tv='Кормление демонов',
		dk='^Your spell critical strikes have a (.+) chance to restore (.+) per level Mana to your demon%.$',
		dv='Ваши критические удары заклинаниями с вероятностью %s восстанавливают %s ед. маны за уровень вашему демону.'},
	[71448]={tk='Bring the Pain',tv='Вестник боли',
		dk='^Increases the critical strike chance of your Searing Pain, Conflagrate and Shadowburn spells by (.+)%.$',
		dv='Увеличивает вероятность критического удара ваших заклинаний "Жгучая боль", "Поджигание" и "Ожог Тьмы" на %s.'},
	[71731]={tk='Destructive Reach',tv='Предел разрушения',
		dk='^Increases the range of your Destruction spells by (.+) and reduces the threat generated by your Destruction spells by (.+)%.$',
		dv='Увеличивает вашу дальность заклинаний разрушения на %s и снижает угрозу, создаваемую вашими заклинаниями разрушения, на %s.'},
	[71732]={tk='Improved Immolate',tv='Улучшенный Жертвенный огонь',
		dk='^Increases the damage done by your Immolate by (.+)%.$',
		dv='Увеличивает урон от заклинания "Жертвенный огонь" на %s.'},
	[72046]={tk='Improved Shadow Bolt',tv='Улучшенная стрела тьмы',
		dk='^Your Shadow Bolt critical strikes has a (.+) chance to increase Shadow damage dealt to the target by (.+) for (.+) sec%.$',
		dv='Ваши критические удары "Стрелой Тьмы" с вероятностью %s увеличивают урон от темной магии, наносимый цели, на %s на %s сек.'},
}

local DB_L = {
	{k='^Next rank:$',v='|nСледующий ранг:'},
	{k='^Instant cast$',v='Мгновенное действие'},
	{k='^Instant$',v='Мгновенное действие'},
	{k='^(.+) Mana$',v='Мана: %s'},
}

local DB_R = {
	{k='^(.+) sec cooldown$',v='Восстановление: %s сек'},
	{k='^(.+) min cooldown$',v='Восстановление: %s мин'},
	{k='^(.+) yd range$',v='Радиус действия: %s м'},
}

CreateFrame("GameTooltip", "MyQuestTooltip", nil, "GameTooltipTemplate" )

local HookSetTalent = GameTooltip.SetTalent
function GameTooltip.SetTalent(self, tabIndex, talentIndex)
	if IsAltKeyDown() then
		MyQuestTooltip:SetOwner(UIParent, "ANCHOR_CURSOR")
		MyQuestTooltip:SetTalent(tabIndex, talentIndex)
		MyQuestTooltip:Show()

		local id = GetTalentId(getglobal("MyQuestTooltipTextLeft1"):GetText())
		if not DB[id] then
			MyQuestTooltip:Hide()
			HookSetTalent(self, tabIndex, talentIndex)
			return
		end
		GameTooltip:AddLine(DB[id].tv, 1, 1, 1)
		GameTooltip:AddLine(DB[id].tk, 1, 1, 1)

		local rank = {string.find(getglobal('MyQuestTooltipTextLeft2'):GetText(), '^Rank (.+)$')}
		if not rank[3] then
			MyQuestTooltip:Hide()
			HookSetTalent(self, tabIndex, talentIndex)
			return
		end
		GameTooltip:AddLine(string.format('|nРанг %s', (rank[3] or "")), 1, 1, 1)

		for i = 3, MyQuestTooltip:NumLines() do
			local c = {getglobal('MyQuestTooltipTextLeft' .. i):GetTextColor()}
			if math_round(c[1], 1) == 1 and math_round(c[2], 2) == 0.13 and math_round(c[3], 2) == 0.13 then
				GameTooltip:AddLine(getglobal('MyQuestTooltipTextLeft' .. i):GetText(), 1, 0.13, 0.13)
			end

			if math_round(c[1], 1) == 1 and math_round(c[2], 2) == 1 and math_round(c[3], 2) == 1 then
				local textL = nil
				for j = 1, table.getn(DB_L) do
					local r = {string.find(getglobal('MyQuestTooltipTextLeft' .. i):GetText(), DB_L[j].k)}
					if r[1] then
						textL = string.format(DB_L[j].v, (r[3] or ""))
					end
				end
				if not textL then -- если перевод не найден
					textL = getglobal('MyQuestTooltipTextLeft' .. i):GetText()
				end

				if getglobal('MyQuestTooltipTextRight'..i):IsVisible() then
					local textR = nil
					for j = 1, table.getn(DB_R) do
						local r = {string.find(getglobal('MyQuestTooltipTextRight' .. i):GetText(), DB_R[j].k)}
						if r[1] then
							textR = string.format(DB_R[j].v, (r[3] or ""))
						end
					end
					if not textR then -- если перевод не найден
						textR = getglobal('MyQuestTooltipTextRight' .. i):GetText()
					end
					GameTooltip:AddDoubleLine(textL, textR, 1,1,1, 1,1,1)
				else
					GameTooltip:AddLine(textL, 1,1,1)
				end
			end

			if math_round(c[1], 1) == 1 and math_round(c[2], 2) == 0.82 and math_round(c[3], 2) == 0 then
				local r = {string.find(getglobal('MyQuestTooltipTextLeft' .. i):GetText(), DB[id].dk)}
				if r[1] then
					GameTooltip:AddLine(string.format(DB[id].dv, (r[3] or ""), (r[4] or ""), (r[5] or "")), 1,0.82,0, 1)
				end
			end
		end
		MyQuestTooltip:Hide()
		GameTooltip:Show()
	else
		HookSetTalent(self, tabIndex, talentIndex)
	end
end

function GetTalentId(title)
	if title == 'Shadowstorm ' then
		title = 'Shadowstorm'
	end

	local res = {string.find(title, "^(%a).- (%a).- (%a).+(%a)$")}
	if not res[1] then
		res = {string.find(title, "^(%a).- (%a)(%a).+(%a)$")}
		if not res[1] then
			res = {string.find(title, "^(%a).-(%a)(%a)(%a)$")}
		end
	end
	return tonumber(GetClassId() .. string.format("%02d", string.len(title)) .. (GetLetterCode(res[3]) + GetLetterCode(res[4]) + GetLetterCode(res[5]) + GetLetterCode(res[6])))
end

function GetClassId()
	local classList = {
		['Warrior'] = 1,
		['Paladin'] = 2,
		['Shaman'] = 3,
		['Hunter'] = 4,
		['Rogue'] = 5,
		['Druid'] = 6,
		['Warlock'] = 7,
		['Mage'] = 8,
		['Priest'] = 9
	}
	return classList[({UnitClass("player")})[1]]
end

function GetLetterCode(letter)
	return string.byte(string.upper(letter)) - 65
end

-- Округляет число до указанной точности
math_round = function(num, idp)
    local mult = 10^(idp or 0)
    return math.floor(num * mult + 0.5) / mult
end
